### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Maskuh**
Here Sam I liked your readme.md in rewrite so I brought it over with a few modifications.

### CODE REVIEW

**Review by wotanut — COMMENTED** [review]
This is great, thank you.

Could you do me a huge favour though and just add a note saying that V1 is outdated and V2 will come soon though please

**Comment by Maskuh** [comment]
Done! Added the note in h2 sizing at the top!

**Comment by wotanut** [comment]
Just reading through your other pr and adding review's, can you add this to there and then i'll close this one please, it'll include merge conflicts if either of these two are merged?

**Review by wotanut — APPROVED** [review]

**Comment by wotanut** [comment]
Thanks :D

**Pull request merged**
